issuer: https://accounts.google.com
# autofix@prod-enforce-fabc.iam.gserviceaccount.com
subject: "114301252256317020592"

permissions:
  actions: read
  checks: write
  contents: write
  pull_requests: write
  statuses: read
  workflows: write # Allow triggering actions when authoring commits.
