issuer: https://accounts.google.com

# epoch-bot@prod-enforce-fabc.iam.gserviceaccount.com
subject: "103350835514269129226"

permissions:
  contents: read
  checks: write
  pull_requests: read

repositories:
- os
