issuer: https://accounts.google.com

# internal-tools: cron-github-label-syncer@internal-tools-1ho6.iam.gserviceaccount.com
subject_pattern: "100141704200657398121"

# to be able to write issues and see the repos if is private
permissions:
  issues: write
  pull_requests: write
  contents: read

repositories: []  # Act over all of the repos in the org.
