issuer: https://accounts.google.com

# staging-images: not in use
# prod-images: lifecycle-devops-collector@prod-images-c6e5.iam.gserviceaccount.com
subject: "109102922315025257155"

permissions:
  actions: read
  checks: read
  contents: read
  issues: read
  metadata: read
  pull_requests: read

repositories:
  - advisories
  - os
